### PR TITLE
Improve unit math

### PR DESCRIPTION
**Pull request by andrewda**
### This depends on #13 

```kotlin
fun main() {
    println(90.deg > 1.rev) // false
    println(PI.rad == 180.deg) // true

    println(300.cm + 2.m) // 500.0 cm
    println(10.m + 200.cm + 8.m + 259.mm) // 20.259 m

    println(1.rev / 90.deg) // 4.0
    println((2 * PI).rad / 15.deg) // 24.0
    println(2.deg / 100.s) // 0.02 °/s

    println(100.cm * 0.5.m) // 5000.0 cm²
    println(0.5.m * 100.cm) // 0.5 m²
    println(0.5.rad * 60.m) // 30.0 rad-min

    println(100.cm * 0.5.m == 0.5.m * 100.cm) // true

    val threeQuarters = PI.rad + 90.deg
    println(threeQuarters) // 4.71238898038469 rad
    println(threeQuarters.convertTo(Revolutions)) // 0.75 rev
    println(threeQuarters.convertTo(Degrees)) // 270.0°
}

```

### CODE REVIEW

**Comment by andrewda** [comment]
Eventually it'd also be nice to be able to do something like `180.deg / 30.s = 6°/s` but I haven't yet been able to figure out quite how to do that...

**Comment by gnawinganimal** [comment]
Wow you added comparisons good idea

**Comment by gnawinganimal** [comment]
Every unit has a `base`, which its equivalent measurement in its field. If you were to convert each `MetricValue` into its equivalent in the base unit, you could get the `Double` result of the expression. Then you could create a new `MetricValue` with the unit of `CompositionUnit`.

**Comment by gnawinganimal** [comment]
Wow that made no sense

**Comment by andrewda** [comment]
No I think that makes sense, let me try it out

**Comment by andrewda** [comment]
Okay @Jamdan2, you can now do the following:

```kotlin
println(2.deg / 100.s) // 0.02 °/s
println(18.m / 6.s) // 3.0 m/s

println(0.5.rad * 60.m) // 30.0 rad-min
```

**Comment by andrewda** [comment]
ping @Jamdan2 😉

**Comment by gnawinganimal** [comment]
Nice

**Pull request merged**
