### PR TITLE
Buttons

### PR DESCRIPTION
**Pull request by gnawinganimal**
Buttons and stuff. To check a value every 20ms you can use
```
{ someValue }.watch {
	onChange {
		// ...
	}
}
```
if `someValue` is a boolean, there are also additional event subscribers `whenTrue` and `whenFalse`.
You can also add listeners to the observed value after it has beed created, like 
```
val watchX = watch { x }
watchX {
	onChange {
		// ...
	}
}
```
Buttons and digital dio ports can be used like this:
```
val button = stickButton(0, 0) {
	onChange {

	}
}
val limitSwitch = digitalInput(0) {
	onChange {

	}
}
```

### CODE REVIEW

**Comment by gnawinganimal** [comment]
Also analog inputs can be used with `analogInput` and `analogInputAverage`.

**Comment by gnawinganimal** [comment]
Thinking of it now, it might be nice to have classes for inputs because then there could be event listeners for any value associated with the inputs, such as `current` and `averageValue`

**Comment by will-hou** [comment]
Very cool! 👍 

Is there any way to check whether a button is being held currently?

**Comment by ghost** [comment]
Doesn't the `whenTrue` subscriber provide this functionality?

**Comment by gnawinganimal** [comment]
Well, no, it just subscribes to the `True` event and then doesn't cancel itself until the listener finishes.

**Comment by gnawinganimal** [comment]
This needs to be merged just because we need to use buttons.

**Pull request merged**
